import type { Project } from "./types";

// TODO(Nicolas) : liens réels, chiffres réels, visuels. Les résultats marqués
// "(à confirmer)" sont du faux contenu réaliste à remplacer.
export const projects: Project[] = [
  {
    slug: "skysearch",
    code: "LFPG",
    title: "SkySearch",
    tagline: { fr: "Chercher un vol comme on parlerait à un agent au comptoir.", en: "Search a flight the way you'd ask an agent at the desk." },
    tags: ["Tech", "Aviation"],
    year: "2026",
    context: {
      fr: "Les moteurs d'horaires obligent à remplir six champs pour une question simple. SkySearch prend une phrase (« vols Paris Lisbonne demain matin ») et renvoie les horaires, avec renvoi vers FlightAware ou Flightradar24 pour le statut temps réel.",
      en: "Schedule search engines make you fill six fields for one simple question. SkySearch takes a sentence and returns flights, with hand-off to FlightAware or Flightradar24 for live status.",
    },
    role: { fr: "Conception, dev front et back, parsing en langage naturel, PWA installable.", en: "Design, front and back-end, natural-language parsing, installable PWA." },
    stack: ["Next.js", "TypeScript", "PWA", "LLM API", "AeroDataBox"],
    result: { fr: "v2 en cours de refonte après audit. Installable hors ligne, requête résolue en moins de 2 s (à confirmer).", en: "v2 being rebuilt after an audit. Installable offline, queries resolved under 2 s (to confirm)." },
    links: [{ label: "GitHub", href: "https://github.com/njegou/skysearch1" }],
  },
  {
    slug: "assistant-agentique",
    code: "HOME",
    title: "Assistant personnel agentique",
    tagline: { fr: "Un majordome self-hosted qui demande la permission avant de casser quelque chose.", en: "A self-hosted butler that asks before doing anything irreversible." },
    tags: ["Tech", "Data"],
    year: "2025",
    context: {
      fr: "Architecture hébergée sur NAS Synology via n8n. Google Calendar sert de source de vérité, un bot Telegram valide les actions irréversibles, l'accès distant passe par Tailscale.",
      en: "Hosted on a Synology NAS via n8n. Google Calendar is the source of truth, a Telegram bot gates irreversible actions, remote access goes through Tailscale.",
    },
    role: { fr: "Architecture complète, workflows n8n, sécurité réseau, prompts des agents.", en: "Full architecture, n8n workflows, network security, agent prompts." },
    stack: ["n8n", "Synology", "Docker", "Telegram Bot API", "Google Calendar API", "Tailscale"],
    result: { fr: "Zéro action destructive sans validation humaine. Tourne 24/7 chez moi.", en: "Zero destructive action without human sign-off. Runs 24/7 at home." },
    links: [],
  },
  {
    slug: "jarvis",
    code: "VOX",
    title: "Jarvis vocal",
    tagline: { fr: "Mot d'activation, oreille locale, cerveau dans le cloud.", en: "Wake word, local ears, cloud brain." },
    tags: ["Tech"],
    year: "2026",
    context: {
      fr: "Assistant vocal standalone : détection du mot d'activation, transcription, synthèse vocale locale, LLM en API pour le raisonnement. Capable de manipuler l'écran.",
      en: "Standalone voice assistant: wake-word detection, transcription, local TTS, LLM over API for reasoning. Can drive the screen.",
    },
    role: { fr: "Conception du pipeline audio, intégration LLM, outils de contrôle de l'écran.", en: "Audio pipeline design, LLM integration, screen-control tools." },
    stack: ["Python", "Whisper", "Piper TTS", "LLM API", "PyAutoGUI"],
    result: { fr: "Latence bouche-à-réponse sous la seconde sur une machine modeste (à confirmer).", en: "Sub-second mouth-to-answer latency on modest hardware (to confirm)." },
    links: [],
  },
  {
    slug: "agent-prospection",
    code: "SLS",
    title: "Agent de prospection LinkedIn",
    tagline: { fr: "Un SDR qui adapte son discours au métier en face, et qui ne dort pas.", en: "An SDR that tailors its pitch to the job title, and never sleeps." },
    tags: ["Tech", "Business"],
    year: "2026",
    context: {
      fr: "Agent IA hybride LinkedIn / email construit sur n8n. Discours généré selon le métier du prospect, relances pilotées par Salesforce Flow.",
      en: "Hybrid LinkedIn / email AI agent built on n8n. Pitch generated from the prospect's role, follow-ups driven by Salesforce Flow.",
    },
    role: { fr: "Brief, parti pris produit, workflows n8n, intégration Salesforce.", en: "Brief, product stance, n8n workflows, Salesforce integration." },
    stack: ["n8n", "Salesforce Flow", "LinkedIn Sales Navigator", "LLM API"],
    result: { fr: "Temps de qualification divisé par 3 sur les premières séquences (à confirmer).", en: "Qualification time cut by 3x on the first sequences (to confirm)." },
    links: [],
  },
  {
    slug: "migration-crm",
    code: "CRM",
    title: "Migration CRM NukkAI",
    tagline: { fr: "Refonte et migration du CRM d'une startup IA de 19 personnes.", en: "Rebuilding and migrating the CRM of a 19-person AI startup." },
    tags: ["Business", "Data"],
    year: "2025",
    context: { fr: "Modèle de données repensé, nettoyage, import, formation de l'équipe commerciale.", en: "Redesigned data model, cleanup, import, sales team onboarding." },
    role: { fr: "Pilotage du projet de bout en bout.", en: "End-to-end project ownership." },
    stack: ["Salesforce", "Data cleaning", "Flow", "Reporting"],
    result: { fr: "Un pipeline lisible par toute l'équipe, reporting hebdo automatisé.", en: "A pipeline the whole team can read, automated weekly reporting." },
    links: [],
  },
  {
    slug: "com-linkedin-nukkai",
    code: "COM",
    title: "Communication LinkedIn NukkAI",
    tagline: { fr: "Faire parler une boîte d'IA explicable sans jargon.", en: "Making an explainable-AI company talk without jargon." },
    tags: ["Business"],
    year: "2024-2026",
    context: { fr: "Gestion et stratégie de la communication LinkedIn de l'entreprise.", en: "Running and shaping the company's LinkedIn communication." },
    role: { fr: "Ligne éditoriale, calendrier, rédaction, visuels, analyse.", en: "Editorial line, calendar, writing, visuals, analytics." },
    stack: ["LinkedIn", "Canva", "Analytics"],
    result: { fr: "Portée mensuelle multipliée (chiffre à compléter).", en: "Monthly reach multiplied (figure to fill in)." },
    links: [{ label: "NukkAI", href: "https://nukk.ai" }],
  },
  {
    slug: "versailles-fc",
    code: "VFC",
    title: "Stratégie omnicanale Versailles FC",
    tagline: { fr: "Plan de communication multicanal pour un club en montée.", en: "Multichannel communication plan for a rising club." },
    tags: ["Business"],
    year: "2025",
    context: { fr: "Projet académique : diagnostic, cibles, canaux, calendrier et KPIs.", en: "Academic project: diagnosis, targets, channels, calendar and KPIs." },
    role: { fr: "Stratégie et recommandations.", en: "Strategy and recommendations." },
    stack: ["Étude de marché", "Persona", "Plan média"],
    result: { fr: "Recommandation présentée au jury.", en: "Recommendation presented to the jury." },
    links: [],
  },
  {
    slug: "liquidtune",
    code: "LQD",
    title: "LiquidTune",
    tagline: { fr: "Des recommandations musicales branchées sur Apple Music.", en: "Music recommendations wired into Apple Music." },
    tags: ["Tech"],
    year: "2025",
    context: { fr: "PWA de recommandation musicale basée sur MusicKit JS.", en: "Music recommendation PWA built on MusicKit JS." },
    role: { fr: "Dev complet.", en: "Full build." },
    stack: ["MusicKit JS", "PWA", "TypeScript"],
    result: { fr: "Prototype fonctionnel.", en: "Working prototype." },
    links: [],
  },
  {
    slug: "stopabo",
    code: "STP",
    title: "StopAbo",
    tagline: { fr: "Voir enfin combien coûtent tous ces abonnements.", en: "Finally see what all those subscriptions cost." },
    tags: ["Tech", "Data"],
    year: "2024",
    context: { fr: "App de suivi d'abonnements : échéances, total mensuel, alertes.", en: "Subscription tracker: due dates, monthly total, alerts." },
    role: { fr: "Conception et dev.", en: "Design and build." },
    stack: ["TypeScript", "PWA", "IndexedDB"],
    result: { fr: "Utilisé au quotidien.", en: "Used daily." },
    links: [],
  },
  {
    slug: "funkie",
    code: "FNK",
    title: "Funkie",
    tagline: { fr: "Création publicitaire pour un petit-déjeuner bio.", en: "Ad creative for an organic breakfast brand." },
    tags: ["Business"],
    year: "2024",
    context: { fr: "Projet académique : concept, accroche, déclinaisons print et social.", en: "Academic project: concept, tagline, print and social variants." },
    role: { fr: "Concept et direction créative.", en: "Concept and creative direction." },
    stack: ["Canva", "Copywriting"],
    result: { fr: "Campagne présentée en cours.", en: "Campaign presented in class." },
    links: [],
  },
  {
    slug: "airlines-db",
    code: "DB",
    title: "Base de données compagnies aériennes",
    tagline: { fr: "Toutes les compagnies, codes OACI/IATA, flottes, dans une base propre.", en: "Every airline, ICAO/IATA codes, fleets, in one clean database." },
    tags: ["Data", "Aviation"],
    year: "2025",
    context: { fr: "Modélisation relationnelle et alimentation d'une base compagnies aériennes.", en: "Relational modelling and loading of an airline database." },
    role: { fr: "Modélisation, import, requêtes.", en: "Modelling, import, queries." },
    stack: ["SQL", "Python", "pandas"],
    result: { fr: "Plus de 5 000 compagnies référencées (à confirmer).", en: "5,000+ airlines referenced (to confirm)." },
    links: [],
  },
];
