import type { Lang } from "./types";

// TODO(Nicolas) : liens réels.
export const socials = {
  linkedin: "https://www.linkedin.com/in/nicolas-xxxx",
  github: "https://github.com/njegou",
  email: "hello@nicolas.example",
};

export const dict = {
  fr: {
    nav: { about: "À propos", projects: "Projets", stack: "Stack", aviation: "Aviation", contact: "Contact", menu: "Menu" },
    hero: {
      eyebrow: "PORTFOLIO / 2026 / N48°48' E002°04'",
      title: ["Je vends,", "je build,", "je vole."],
      sub: "Nicolas. Commerce et marketing en startup IA le jour, agents et systèmes self-hosted le soir, formation pilote le week-end.",
      cta: "Voir les projets",
      cta2: "Me contacter",
      scroll: "Défiler",
    },
    about: {
      label: "À propos",
      title: "Trois identités, une seule cabine.",
      p1: "Alternant en com, marketing et sales chez NukkAI, une startup parisienne qui fait de l'IA explicable et hybride. Je passe mes journées entre Salesforce, LinkedIn et des prospects qui veulent comprendre ce qu'il y a dans la boîte noire.",
      p2: "Le reste du temps je construis : agents IA, PWA, automatisations n8n sur un NAS dans mon placard. Je n'aime pas attendre qu'un outil existe.",
      p3: "Et je me forme au pilotage. L'aviation m'a appris la checklist, la radio sans bruit inutile, et qu'un plan B se prépare avant le décollage.",
      facts: [
        ["Base", "Saint-Cyr-l'École, 78"],
        ["Rôle", "Alternant com / marketing / sales"],
        ["Études", "BUT TC, diplômé 2027"],
        ["Formation", "Pilote en cours"],
      ],
    },
    projects: {
      label: "Projets",
      title: "Plan de vol.",
      sub: "Filtre par tag. Ouvre une carte pour le détail.",
      all: "Tous",
      open: "Ouvrir",
      close: "Fermer",
      context: "Contexte",
      role: "Rôle",
      stack: "Stack",
      result: "Résultat",
      links: "Liens",
      drag: "Scroll pour défiler",
    },
    stack: {
      label: "Stack & compétences",
      title: "Ce que je sais faire, et avec quoi.",
      business: "Business",
      tech: "Tech",
      businessItems: ["Prospection et cycle de vente B2B", "Salesforce (admin, Flow, reporting)", "Stratégie de communication", "Marketing de contenu LinkedIn", "Étude de marché et persona", "Pitch et négociation"],
      techItems: ["TypeScript, Next.js, PWA", "n8n, Docker, Synology, Tailscale", "Agents IA, prompts, API LLM", "Python, SQL, pandas", "Three.js, GSAP, animation web", "Salesforce Flow, intégrations API"],
    },
    aviation: {
      label: "Aviation",
      title: "Tour de piste.",
      p: "Je me forme au pilotage privé. Ce n'est pas un hobby décoratif : c'est la discipline qui structure tout le reste. Procédures, phraséologie, gestion de la charge mentale, décision sous contrainte.",
      stats: [
        ["Statut", "Élève pilote"],
        ["Terrain", "LFPN Toussus"],
        ["Avion", "DR400 / PA28"],
        ["Objectif", "PPL(A)"],
      ],
      strip: "FPL N-DMXG DR40 LFPN 1030 LFPT LFPN 0045",
    },
    contact: {
      label: "Contact",
      title: "Parlons-en.",
      sub: "Alternance, freelance, projet tech, ou juste discuter d'aviation. Réponse sous 48 h.",
      name: "Nom",
      email: "Email",
      message: "Message",
      send: "Envoyer",
      sending: "Envoi...",
      sent: "Message envoyé. Je reviens vers toi vite.",
      error: "L'envoi a échoué. Écris-moi directement par email.",
      noEndpoint: "Formulaire non configuré : ajoute NEXT_PUBLIC_CONTACT_ENDPOINT.",
    },
    footer: { made: "Conçu et codé par Nicolas", rights: "Tous droits réservés", top: "Haut de page" },
    marquee: ["Next.js", "TypeScript", "n8n", "Salesforce", "Three.js", "GSAP", "Python", "Docker", "LinkedIn", "PPL(A)", "Agents IA", "PWA"],
    konami: { title: "Cleared for takeoff", sub: "Piste 25, vent 240/08. Bon vol." },
    theme: { dark: "Passer en mode sombre", light: "Passer en mode clair" },
    lang: "Switch to English",
    preloader: "Alignement piste",
  },
  en: {
    nav: { about: "About", projects: "Projects", stack: "Stack", aviation: "Aviation", contact: "Contact", menu: "Menu" },
    hero: {
      eyebrow: "PORTFOLIO / 2026 / N48°48' E002°04'",
      title: ["I sell,", "I build,", "I fly."],
      sub: "Nicolas. Sales and marketing at an AI startup by day, AI agents and self-hosted systems by night, pilot training on weekends.",
      cta: "See projects",
      cta2: "Get in touch",
      scroll: "Scroll",
    },
    about: {
      label: "About",
      title: "Three identities, one cockpit.",
      p1: "Apprentice in comms, marketing and sales at NukkAI, a Paris startup building explainable, hybrid AI. My days go between Salesforce, LinkedIn and prospects who want to know what's inside the black box.",
      p2: "The rest of the time, I build: AI agents, PWAs, n8n automations on a NAS in my closet. I don't like waiting for a tool to exist.",
      p3: "And I'm training as a pilot. Aviation taught me the checklist, radio with no wasted words, and that plan B gets prepared before takeoff.",
      facts: [
        ["Base", "Saint-Cyr-l'École, near Versailles"],
        ["Role", "Comms / marketing / sales apprentice"],
        ["Studies", "BUT TC, graduating 2027"],
        ["Training", "Student pilot"],
      ],
    },
    projects: { label: "Projects", title: "Flight plan.", sub: "Filter by tag. Open a card for details.", all: "All", open: "Open", close: "Close", context: "Context", role: "Role", stack: "Stack", result: "Outcome", links: "Links", drag: "Scroll to browse" },
    stack: {
      label: "Stack & skills",
      title: "What I do, and what I do it with.",
      business: "Business",
      tech: "Tech",
      businessItems: ["B2B prospecting and sales cycle", "Salesforce (admin, Flow, reporting)", "Communication strategy", "LinkedIn content marketing", "Market research and personas", "Pitching and negotiation"],
      techItems: ["TypeScript, Next.js, PWA", "n8n, Docker, Synology, Tailscale", "AI agents, prompting, LLM APIs", "Python, SQL, pandas", "Three.js, GSAP, web animation", "Salesforce Flow, API integrations"],
    },
    aviation: {
      label: "Aviation",
      title: "Traffic pattern.",
      p: "I'm training for a private pilot licence. Not a decorative hobby: it's the discipline that structures everything else. Procedures, phraseology, workload management, decisions under constraint.",
      stats: [["Status", "Student pilot"], ["Airfield", "LFPN Toussus"], ["Aircraft", "DR400 / PA28"], ["Goal", "PPL(A)"]],
      strip: "FPL N-DMXG DR40 LFPN 1030 LFPT LFPN 0045",
    },
    contact: {
      label: "Contact",
      title: "Let's talk.",
      sub: "Apprenticeship, freelance, a tech project, or just aviation chat. Reply within 48 h.",
      name: "Name", email: "Email", message: "Message", send: "Send", sending: "Sending...",
      sent: "Message sent. I'll get back to you soon.",
      error: "Sending failed. Email me directly instead.",
      noEndpoint: "Form not configured: set NEXT_PUBLIC_CONTACT_ENDPOINT.",
    },
    footer: { made: "Designed and coded by Nicolas", rights: "All rights reserved", top: "Back to top" },
    marquee: ["Next.js", "TypeScript", "n8n", "Salesforce", "Three.js", "GSAP", "Python", "Docker", "LinkedIn", "PPL(A)", "AI agents", "PWA"],
    konami: { title: "Cleared for takeoff", sub: "Runway 25, wind 240/08. Safe flight." },
    theme: { dark: "Switch to dark mode", light: "Switch to light mode" },
    lang: "Passer en français",
    preloader: "Runway alignment",
  },
} as const satisfies Record<Lang, unknown>;

export type Dict = (typeof dict)["fr"];
